---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shinycssloaders)
library(ggplot2)

freqpoly <- function(x1, x2, binwidth = 0.1, xlim = c(-3, 3)) {
  df <- data.frame(
    x = c(x1, x2),
    g = c(rep("x1", length(x1)), rep("x2", length(x2)))
  )

  ggplot(df, aes(x, colour = g)) +
    geom_freqpoly(binwidth = binwidth, size = 1) +
    coord_cartesian(xlim = xlim)
}

t_test <- function(x1, x2) {
  test <- t.test(x1, x2)

  # use sprintf() to format t.test() results compactly
  sprintf(
    "p value: %0.3f\n[%0.2f, %0.2f]",
    test$p.value, test$conf.int[1], test$conf.int[2]
  )
}
```

## Inputs {.sidebar}

### Sample 1

```{r}
numericInput("n1", label = "n", value = 1000, min = 1)
numericInput("mean1", label = "µ", value = 0, step = 0.1)
numericInput("sd1", label = "σ", value = 0.5, min = 0.1, step = 0.1)
```

### Sample 2

```{r}
numericInput("n2", label = "n", value = 1000, min = 1)
numericInput("mean2", label = "µ", value = 0, step = 0.1)
numericInput("sd2", label = "σ", value = 0.5, min = 0.1, step = 0.1)
```

### Histogram controls

```{r}
numericInput("binwidth", label = "Bin width", value = 0.1, step = 0.1)
sliderInput("range", label = "range", value = c(-3, 3), min = -5, max = 5)
```

```{r}
x1 <- reactive(rnorm(input$n1, input$mean1, input$sd1))
x2 <- reactive(rnorm(input$n2, input$mean2, input$sd2))
```


## Column {data-width=650}


### Histogram

```{r}
renderPlot({
  Sys.sleep(5)
  freqpoly(x1(), x2(), binwidth = input$binwidth, xlim = input$range)
}, res = 96)
```

## Column {data-width=350}

### p-value

```{r}
renderText({
  t_test(x1(), x2())
})
```
